### ISSUE TITLE
Wrong canonical for detail pages if additional parameter exists

### ISSUE THREAD

**Issue by poomer1988** [clickstorm/cs_seo#231]
If you put an additional parameter on a detail pages, the canonical will be wrong.
For example: 

Correct:
`de/overview/detail-record/ -> canonical de/overview/detail-record/`

Wrong:
`de/overview/detail-record/?tracking=1 -> canonical de/overview/`

**Comment by mhirdes** [comment]
If you use an older version like cs_seo 2.x you have to add the tracking param to lib.currentUrl.typolink.parameter.addQueryString.exclude
 https://github.com/clickstorm/cs_seo/blob/2x/Configuration/TypoScript/Setup/lib.currenUrl.ts 

Since cs_seo 3.x only parameters were included, if they were needed to calculate the cHash.

**Comment by poomer1988** [comment]
We are current using the 3.1.0. If i set the lib.currentUrl.typolink.parameter.addQueryString.exclude it works, otherwise not

**Comment by mhirdes** [comment]
https://github.com/clickstorm/cs_seo/blob/3x/Configuration/TypoScript/Setup/lib.currenUrl.ts I've checked again. Here only cHash parameter will get included. Please check your cHash config. Also to use lib.currentUrl.typolink.parameter.addQueryString.exclude is a workaround. In cs_seo 4 we will use the core option $GLOBALS['TYPO3_CONF_VARS']['FE']['additionalCanonicalizedUrlParameters']

**Comment by mhirdes** [comment]
also lib.currentUrl.typolink.parameter.addQueryString is not set in cs_seo 3.
