### ISSUE TITLE
Problems with Workspace

### ISSUE THREAD

**Issue by Webschmiede** [clickstorm/cs_seo#300]
We have a TYPO3 10.4.16 installation and the editors work in a workspace. In live mode everything works fine. In the workspace, the SEO content analysis displays incorrect values. Is there something to consider or have I forgotten a configuration? I am using CS_SEO 6.6.0.

**Comment by clickstorm** [comment]
Currently this feature does not work for workspaces. Currently the TYPO3 login page would be evaluated, because of missing cookies for the request. 

I could fix this. But there are 2 other points: 
1. To generate a preview url each time a new sys_preview record will be stored. -> Scheduler Task to clean up this table should be active.
2. Currently the results of the avaluation are stored in a different table. We could also store each evaluation result for each preview. But then we have also to clean them up. Or I ignore the preview, but if you then switch to the live workspace, you'll see the same evaluation result.

The easiest way would be to hide the evaluation in the page module if you are currently in a workspace. Would this be ok?

**Comment by Webschmiede** [comment]
Thanks for your quick reply. This information is enough for me. Just thought I forgot something to configure :-)
