### ISSUE TITLE
minDescription being forced due to faulty condition

### ISSUE THREAD

**Issue by fjacobi** [clickstorm/cs_seo#328]
Hej, during an upgrade I just ran into this issue.

https://github.com/clickstorm/cs_seo/blob/main/Configuration/TCA/Overrides/pages.php#L16

The field is a boolean, so it's never empty?

**Comment by mhirdes** [comment]
For me it works. Can you check it again?
 
https://www.php.net/manual/en/function.empty.php 

Returns true if var does not exist or has a value that is empty or equal to zero, aka falsey, see conversion to boolean. Otherwise returns false.

https://onlinephp.io?s=s7EvyCjg5eLlUsmtDEssUrBVSEvMKU61Bgllpmmk5haUVGpA5DQ1Fap5uThTkzPyFdQ9ixXAcurWnLxctQqpQD2osnn5JTAVQAUA&v=8.2.13
