### ISSUE TITLE
enhancing the no-index checkbox

### ISSUE THREAD

**Issue by Toccamonium** [clickstorm/cs_seo#39]
Hi,
would it be possible, to add a dropdown instead of the checkbox in the seo tab to have more options available, like other CMS do it? Would be a nice feature to remove pages from index but still use the links power of it. Thx!

![17-01-_2017_13-21-44](https://cloud.githubusercontent.com/assets/1674576/22020548/32cc348a-dcb9-11e6-9518-349328affd2a.png)

**Comment by mhirdes** [comment]
Hi,

thanks for your request. I find it difficult to explain an editor when he should use what option. Therefore I want to keep the input fields as simply as possible. Maybe it is a better way to change the value from noindex,nofollow to noindex,follow? Furthermore to add index,follow to the page is not necessary because this is the default.

**Comment by Toccamonium** [comment]
Hi,
well, to set it to noindex,follow sounds good for me. Would appreciate to see this in the next update. Thx!

**Comment by mhirdes** [comment]
Hi,
sry that I answer that late. To override the default behaviour is already possible in cs_seo 1.8.5. You have to write the TypoScript

`page.meta.robots = noindex,follow`

This works for pages.
Maybe in version 2.x I will include another configuration option. 

I hope this is a workaround for you.

**Comment by Toccamonium** [comment]
thanks for this info!
