### ISSUE TITLE
Locale is missing if only one language is active

### ISSUE THREAD

**Issue by PaperCoder** [clickstorm/cs_seo#78]
We've got a project with only one active language. But our URLs all have a locale in them (eg www.example.com/de/index, ...), as we don't know if there will be another language in the future. 

Our sitemap.xml is currently missing the locale in the url. If we add a second language, the locale will be added to the sitemap urls. What is missing in our configuration?

```
# SEO
plugin.tx_csseo {
    social {
        defaultImage = /images/logo.png
        openGraph.image.width = 1200
        openGraph.image.height =
        twitter.image.width = 1200
        twitter.image.height =
    }
    hreflang {
        enable = 1
        ids = 0,0
        keys = x-default,de
    }
    sitemap {
        pages.languageUids = 0
    }
}
```

**Comment by mhirdes** [comment]
Hi. This sounds like a wrong realURL configuration. If you set valueDefault and define your language prefix in the preVars valueMap this should work. Otherwise both versions are possible (with and without language prefix), this is duplicate content which should be avoid. Does this information solve your problem?

**Comment by PaperCoder** [comment]
You put me on the right track :) We had a correct `valueDefault` and `preVars valueMap`, but we've forgotten to add the `defaultGetVars.L = 0` in our typoscript config. Thx for helping
